version: '3.7'

services: 
  gunicorn:
    image: flaskdocker:latest
    container_name: gunicorn
    # command: gunicorn todoapi:app -c todoapi/config/gunicorn_settings.py
    ports: 
      - '5000:5000'  #5000ポートで待ち受けて、5000ポートで内部通信(gunicorn_settings.pyが拾う)
    networks:
      - nginx_network
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on: 
      - gunicorn
    ports: 
      - '80:80'  #80ポートで待ち受けて、80ポートで内部通信(default.confが拾う)
    networks:
      - nginx_network
    volumes: 
     - ./todoapi/config/default.conf:/etc/nginx/conf.d/default.conf

networks:
  nginx_network:
    driver: bridge
